"""Portfolio modell

Revision ID: 2a1ec7b31955
Revises: 83827ae33570
Create Date: 2021-12-14 13:44:48.193482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1ec7b31955'
down_revision = '83827ae33570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_title', sa.String(length=50), nullable=True),
    sa.Column('portfolio_detail', sa.String(length=50), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    # ### end Alembic commands ###
