"""blog model

Revision ID: 83827ae33570
Revises: 0aa00f1ea984
Create Date: 2021-12-14 01:13:34.076348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83827ae33570'
down_revision = '0aa00f1ea984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_title', sa.String(length=50), nullable=True),
    sa.Column('blog_detail', sa.String(length=50), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
