"""about resume model added

Revision ID: a182d8080d29
Revises: f4d16562861c
Create Date: 2021-12-13 16:14:08.968274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a182d8080d29'
down_revision = 'f4d16562861c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_text', sa.Text(), nullable=True),
    sa.Column('second_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience_title', sa.String(length=100), nullable=True),
    sa.Column('experience_info', sa.String(length=100), nullable=True),
    sa.Column('experience_content', sa.Text(), nullable=True),
    sa.Column('education_title', sa.String(length=100), nullable=True),
    sa.Column('education_info', sa.String(length=100), nullable=True),
    sa.Column('education_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('home', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('home', sa.Column('surname', sa.String(length=50), nullable=True))
    op.drop_column('home', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home', sa.Column('text', sa.TEXT(), nullable=True))
    op.drop_column('home', 'surname')
    op.drop_column('home', 'name')
    op.drop_table('resume')
    op.drop_table('about')
    # ### end Alembic commands ###
