"""portfolio update

Revision ID: e5657dcc38bd
Revises: 2a1ec7b31955
Create Date: 2021-12-16 14:19:53.628274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5657dcc38bd'
down_revision = '2a1ec7b31955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'link')
    # ### end Alembic commands ###
